/*=============================================== Utils ===============================================*/

import { Utils } from "tsx-library-julseb"

const {
    calculateTotalSum,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    detectLanguage,
    formatHour,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    passwordRegex,
    emailRegex,
    scrollToTop,
    slugify,
    unslugify,
    uuid,
} = Utils

export {
    calculateTotalSum,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    detectLanguage,
    formatHour,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    passwordRegex,
    emailRegex,
    scrollToTop,
    slugify,
    unslugify,
    uuid,
}
